#Name Of the project
PROJECT_NAME=ATM_MACHINE
TEST_PROJ_NAME = Test_$(PROJECT_NAME)

# Output directory
BUILD= build


#SOURCE PATH
VPATH = SRC INCLUDE

#All source code files
SRC = main.c\
src/atm.c

# All test source files
TEST_SRC = src/atm.c\
test/test_atm.c\
unity/unity.c\


